---
server:
  port: 8080
  contextPath: /PortScanAPI
---
spring:
  profiles: local,dev
datasource:
  portScanApp:
    url: jdbc:h2:~/portScanDB
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  portScanApp:
    url: jdbc:mysql://localhost:3306/portScanDB
    username: root
    password: 
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

